name: police_smart
description: بوابة ذكية خاصة بجهاز الشرطة الفلسطينية

publish_to: 'none' # لأن المشروع تجريبي

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # واجهات
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0

  # ادارة الحالة والتنقل
  provider: ^6.1.2

  # قواعد بيانات محلية
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # التوثيق + تتبع الجهاز
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.2

  # الشبكات
  http: ^1.2.1

  # الخرائط (لاحقًا)
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icons/
